name: Generate Changelog

on:
  release:
    types: [published, edited]
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:
  gen-changelog:
    runs-on: ubuntu-22.04
    environment: genlog_gen_token
    steps:
    - uses: actions/checkout@v4

    - name: install pkgs
      run:  |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update && sudo apt install -y zip grep sudo ruby rubygems git ssh ruby-dev gcc make
            sudo $(which gem) install specific_install

    - name: install github-changelog-generator
      run:  |
            git clone https://github.com/github-changelog-generator/github-changelog-generator -b v1.16.4
            cd github-changelog-generator/
            sudo $(which gem) build github_changelog_generator.gemspec
            sudo $(which gem) install -N github_changelog_generator-1.16.4.gem

    - name: run github-changelog-generator
      env:
            CHANGELOG_GEN_TOKEN: ${{ secrets.CHANGELOG_GEN_TOKEN }}
      run:  |
            pwd
            $(which ruby) $(which github_changelog_generator) -u Zoxcore -p qTox_enhanced \
               --exclude-tags "v1.0,v1.2,v1.2.1,v1.2.2,v1.2.3,v1.2.4,v1.3.0,v1.4.0,v1.4.1,v1.4.1.1,v1.5.0,v1.5.1,v1.5.2,v1.6.0,v1.7.0,v1.7.1,v1.8.0,v1.8.1,v1.9.0,v1.10.0,v1.10.1,v1.10.2,v1.11.0,v1.12.0,v1.12.1,v1.13.0,v1.14.0,v1.14.1,v1.15.0,v1.16.0,v1.16.1,v1.16.2,v1.16.3,v1.17.0,v1.17.1,v1.17.2,v1.17.3,v1.17.4,v1.17.5,nightly" \
               --token "$CHANGELOG_GEN_TOKEN"

    - name: chmod
      run:  |
            sudo chmod a+r /home/runner/work/qTox_enhanced/qTox_enhanced/CHANGELOG.md
            ls -rattlh

    - name: upload CHANGELOG file
      uses: actions/upload-artifact@v4
      with:
        name: Changelog
        path: |
          /home/runner/work/qTox_enhanced/qTox_enhanced/CHANGELOG.md

