name: nixos tests

on:
  push:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
     - '.github/workflows/startup-tests.yml'
     - '.github/workflows/change_log.yml'
  pull_request:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
     - '.github/workflows/startup-tests.yml'
     - '.github/workflows/change_log.yml'

jobs:
    compile:
        name: nixos test
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v4
          - name: Run test
            uses: addnab/docker-run-action@v3
            with:
                image: nixos/nix:latest
                options: -v ${{ github.workspace }}:/work
                run: |
                    id;ls -al /work/; # compile command here
                    nix-build /work/buildscripts/nixos_qtox.nix
